import { connectSolanaWallet, walletState, sendSplToken, executeChainBackedTrade, signSerializedTransaction, detectSolanaWalletProvider, readWalletPortfolio, onWalletAccountChanged } from './solana-client.js';
import { connectRobinhood, getPonsConfig, launchPonsV2, readPonsLaunch, buyPons, sellPons, PONS_V2 } from './pons-v2.js';
let sessionToken=null;
const nativeFetch=window.fetch.bind(window);
window.fetch=(input,init={})=>{const url=typeof input==='string'?input:input.url; if(sessionToken && url.startsWith('/api/')){const h=new Headers(init.headers||{});h.set('Authorization',`Bearer ${sessionToken}`);init={...init,headers:h}} return nativeFetch(input,init)};
function b64(bytes){let x='';for(const b of bytes)x+=String.fromCharCode(b);return btoa(x)}
async function authenticateWallet(w){
 const c=await nativeFetch('/api/auth/challenge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({wallet:w.publicKey})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()});
 if(!w.provider?.signMessage) throw new Error('wallet_sign_message_not_supported');
 const sig=await w.provider.signMessage(new TextEncoder().encode(c.message),'utf8');
 const signature=b64(sig.signature||sig);
 const v=await nativeFetch('/api/auth/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({wallet:w.publicKey,nonce:c.nonce,signature})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()});
 sessionToken=v.token; return v;
}
const fallback=[
{name:'Anduril PreStocks',symbol:'ANDURIL',contract_address:'PresTj4Yc2bAR197Er7wz4UUKSfqt6FryBEdAriBoQB',markPrice:153.94648367,markValuation:136196308976,tokenPrice:157.72755883,impliedValuation:139541422604,image:'https://www.prestocks.com/logos/anduril.png'},
{name:'Anthropic PreStocks',symbol:'ANTHROPIC',contract_address:'Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw',markPrice:1050.44176843,markValuation:1720983186253,tokenPrice:1052.12506369,impliedValuation:1723741000088,image:'https://www.prestocks.com/logos/anthropic.png'},
{name:'Figure AI PreStocks',symbol:'FIGUREAI',contract_address:'PreZad18qfPtbxNpMtMuAuX2zVpvkEU8DnJx56faCWd',markPrice:181.8939899,markValuation:39657798034,tokenPrice:181.91997802,impliedValuation:39663464145,image:'https://www.prestocks.com/logos/figureai.png'},
{name:'Kalshi PreStocks',symbol:'KALSHI',contract_address:'PreLWGkkeqG1s4HEfFZSy9moCrJ7btsHuUtfcCeoRua',markPrice:893.11947124,markValuation:32484588776,tokenPrice:860.81568097,impliedValuation:31309633603,image:'https://www.prestocks.com/logos/kalshi.png'},
{name:'Neuralink PreStocks',symbol:'NEURALINK',contract_address:'PrekqLJvJ3qVdXmBGDiexvwUTF4rLFDa6HWS4HJbw9S',markPrice:336.79705453,markValuation:64158171576,tokenPrice:424.54027376,impliedValuation:80872820466,image:'https://www.prestocks.com/logos/neuralink.png'},
{name:'OpenAI PreStocks',symbol:'OPENAI',contract_address:'PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF',markPrice:995.56955666,markValuation:1233441287355,tokenPrice:1127.221603,impliedValuation:1396548996348,image:'https://www.prestocks.com/logos/openai.png'},
{name:'Polymarket PreStocks',symbol:'POLYMARKET',contract_address:'Pre8AREmFPtoJFT8mQSXQLh56cwJmM7CFDRuoGBZiUP',markPrice:144.29858563,markValuation:14231558175,tokenPrice:142.15989838,impliedValuation:14020628512,image:'https://www.prestocks.com/logos/polymarket.png'},
{name:'SpaceX PreStocks',symbol:'SPACEX',contract_address:'PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh',markPrice:152.62406151,markValuation:2001071028648,tokenPrice:116.46045229,impliedValuation:1526925930061,image:'https://www.prestocks.com/logos/spacex.png'}];
let assets=[...fallback], selected='OPENAI', marketType='threshold', wallet=null, markets=[], config={}, vault={balances:{USDC:0}}, positions=[], lastWalletPortfolio=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], trader=()=>wallet?.publicKey||'guest';
const money=n=>Number(n)>=1e12?`$${(Number(n)/1e12).toFixed(2)}T`:Number(n)>=1e9?`$${(Number(n)/1e9).toFixed(1)}B`:`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const premium=a=>((Number(a.tokenPrice)/Number(a.markPrice))-1)*100, short=x=>x?`${x.slice(0,4)}…${x.slice(-4)}`:'guest';
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function navigate(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));if(v==='wallet')loadWalletCenter();if(v==='commerce')loadCommerce();if(v==='vault')loadVault();if(v==='home')loadV2Home();if(v==='credit')loadCredit();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));
function renderAssets(){
 $('#assetCount').textContent=assets.length; $('#ticker').innerHTML=assets.map(a=>{const p=premium(a);return `<div class="tick ${p>=0?'pos':'neg'}"><b>${a.symbol}</b>${p>=0?'+':''}${p.toFixed(1)}% premium</div>`}).join('');
 $('#assetGrid').innerHTML=assets.map(a=>{const p=premium(a);return `<article class="asset-card" data-asset-card="${a.symbol}"><div class="asset-head"><img class="asset-logo" src="${a.image||''}" alt=""/><span class="premium ${p>=0?'pos':'neg'}">${p>=0?'+':''}${p.toFixed(1)}%</span></div><h3>${a.name.replace(' PreStocks','')}</h3><span class="sym">${a.symbol}</span><div class="price">${money(a.tokenPrice)}</div><div class="valuation">Implied ${money(a.impliedValuation)}</div><div class="asset-actions"><button data-quick-buy="${a.symbol}">Buy</button><button data-quick-auto="${a.symbol}">Auto</button><button data-asset="${a.symbol}">More</button></div></article>`}).join('');
 $('#assetPicker').innerHTML=assets.map(a=>`<button class="pick ${a.symbol===selected?'active':''}" data-pick="${a.symbol}">${a.symbol}</button>`).join('');
 refreshSwapTargets(); $('[data-asset]').forEach(b=>b.onclick=()=>openAsset(b.dataset.asset)); $('[data-quick-buy]').forEach(b=>b.onclick=()=>buyUnderlying(assets.find(a=>a.symbol===b.dataset.quickBuy))); $$('[data-quick-auto]').forEach(b=>b.onclick=()=>scheduleRecurring(assets.find(a=>a.symbol===b.dataset.quickAuto))); $$('[data-pick]').forEach(b=>b.onclick=()=>{selected=b.dataset.pick;renderAssets();buildFields()});
}
function refreshSwapTargets(){
 const to=$('#swapTo');if(!to)return;
 const current=to.value||'USDC';
 to.innerHTML='<option value="USDC">USDC</option>'+assets.map(a=>`<option value="${a.contract_address}">${a.symbol} · PreStock</option>`).join('');
 if([...to.options].some(o=>o.value===current))to.value=current;
}
function renderMarketFeed(){
 $('#marketCount').textContent=markets.length; const open=markets.filter(m=>m.status==='OPEN');
 $('#marketFeed').innerHTML=open.slice(0,14).map(m=>{const y=Math.round((m.yesProbability??.5)*100);return `<article class="feed-card" data-mid="${m.id}"><div class="top"><div><span class="kicker">${(m.rule?.type||'MARKET').replaceAll('_',' ').toUpperCase()}</span><h3>${m.question}</h3></div><span class="status-pill">${m.symbol}</span></div><div class="feed-meta"><span>${money(m.volume||0)} volume</span><span>${m.trades?.length||0} trades</span><span>${m.resolveAt}</span></div><div class="feed-prices"><button class="quicktrade yes" data-side="YES"><small>BUY YES</small><b>${y}¢</b></button><button class="quicktrade no" data-side="NO"><small>BUY NO</small><b>${100-y}¢</b></button></div></article>`}).join('');
 $$('.quicktrade').forEach(b=>b.onclick=async()=>{const card=b.closest('[data-mid]');const shares=Number(prompt(`How many ${b.dataset.side} shares?`,'10')||0);if(shares>0)await trade(card.dataset.mid,b.dataset.side,shares)});
}
function openAsset(sym){const a=assets.find(x=>x.symbol===sym),p=premium(a);$('#assetDialogContent').innerHTML=`<div class="dialog-hero"><img src="${a.image||''}" alt=""/><div><span class="kicker">PRESTOCK</span><h2>${a.name.replace(' PreStocks','')}</h2><p>${a.symbol} · ${a.contract_address.slice(0,6)}…${a.contract_address.slice(-5)}</p></div></div><div class="stat-grid"><div class="stat"><span>Token price</span><b>${money(a.tokenPrice)}</b></div><div class="stat"><span>Mark price</span><b>${money(a.markPrice)}</b></div><div class="stat"><span>Implied valuation</span><b>${money(a.impliedValuation)}</b></div><div class="stat"><span>Mark premium</span><b>${p>=0?'+':''}${p.toFixed(2)}%</b></div></div><div class="idea-list"><button class="idea buy-underlying"><b>Buy / sell 24/7</b><small>Execute the exact mint through Jupiter Swap V2.</small></button><button class="idea recurring-buy"><b>Schedule recurring buy</b><small>Daily, weekly or monthly USDC allocation.</small></button><button class="idea social-signal"><b>Share a thesis</b><small>Create a copyable social signal tied to this mint.</small></button><button class="idea" data-jump="threshold"><b>Program a payoff</b><small>Create a fully collateralized equity instrument.</small></button><button class="idea" data-jump="premium"><b>Premium convergence</b><small>Trade token-vs-mark dislocation.</small></button><button class="idea" data-jump="relative"><b>Relative value</b><small>Company vs company.</small></button></div>`;$('#assetDialog').showModal();$('.buy-underlying').onclick=()=>buyUnderlying(a);$('.recurring-buy').onclick=()=>scheduleRecurring(a);$('.social-signal').onclick=()=>shareSignal(a);$$('[data-jump]').forEach(x=>x.onclick=()=>{selected=sym;marketType=x.dataset.jump;$('#assetDialog').close();navigate('lab');syncType();renderAssets();buildFields()})}
function basketMembers(name){if((name||'').startsWith('Frontier'))return ['OPENAI','ANTHROPIC','FIGUREAI'];if((name||'').startsWith('Future'))return ['SPACEX','ANDURIL','NEURALINK'];if((name||'').startsWith('Prediction'))return ['KALSHI','POLYMARKET'];return assets.map(x=>x.symbol)}
function marketQuestion(){const a=assets.find(x=>x.symbol===selected), expiry=$('#expiry')?.value||'2027-06-30', other=$('#other')?.value;if(marketType==='threshold')return `Will ${a.symbol} implied valuation be above $${$('#target')?.value||0}B by ${expiry}?`;if(marketType==='price')return `Will ${a.symbol} trade above $${$('#priceTarget')?.value||0} by ${expiry}?`;if(marketType==='premium')return `Will ${a.symbol} token premium to mark be within ${$('#premiumBand')?.value||5}% by ${expiry}?`;if(marketType==='relative')return `Will ${a.symbol} outperform ${other} through ${expiry}?`;if(marketType==='spread')return `Will ${a.symbol}/${other} valuation ratio finish above its launch ratio by ${expiry}?`;if(marketType==='move')return `Will ${a.symbol} move at least ${$('#movePct')?.value||20}% in either direction from launch by ${expiry}?`;if(marketType==='leader')return `Will ${a.symbol} be the top-performing PreStock in ${$('#leaderUniverse')?.value||'All 8 PreStocks'} by ${expiry}?`;if(marketType==='pricezone')return `Will ${a.symbol} finish between $${$('#zoneLow')?.value} and $${$('#zoneHigh')?.value} by ${expiry}?`;if(marketType==='valuezone')return `Will ${a.symbol} implied valuation finish between $${$('#zoneLow')?.value}B and $${$('#zoneHigh')?.value}B by ${expiry}?`;if(marketType==='gain')return `Will ${a.symbol} gain at least ${$('#returnPct')?.value||15}% from launch by ${expiry}?`;if(marketType==='shield')return `Will ${a.symbol} avoid falling more than ${$('#returnPct')?.value||15}% from launch by ${expiry}?`;if(marketType==='duel')return `Will ${a.symbol} outperform ${other} by at least ${$('#marginPct')?.value||5} percentage points by ${expiry}?`;if(marketType==='green')return `Will at least ${$('#greenCount')?.value||2} members of ${$('#basket')?.value||'the basket'} finish above launch by ${expiry}?`;return `Will the ${$('#basket')?.value||'PreStocks basket'} finish above its launch level by ${expiry}?`;}
function buildFields(){const a=assets.find(x=>x.symbol===selected);let h='';const others=()=>assets.filter(x=>x.symbol!==selected).map(x=>`<option>${x.symbol}</option>`).join('');if(marketType==='threshold')h=`<div class="field"><label>Target implied valuation</label><input id="target" type="number" value="${Math.round(a.impliedValuation/1e9/50)*50}"/><small>USD billions</small></div>`;if(marketType==='price')h=`<div class="field"><label>Token price target</label><input id="priceTarget" type="number" step="0.01" value="${(a.tokenPrice*1.2).toFixed(2)}"/></div>`;if(marketType==='premium')h=`<div class="field"><label>Absolute premium band</label><input id="premiumBand" type="number" value="5"/><small>Percent from mark</small></div>`;if(['relative','spread','duel'].includes(marketType))h=`<div class="field"><label>Against</label><select id="other">${others()}</select></div>`+(marketType==='duel'?`<div class="field"><label>Winning margin</label><input id="marginPct" type="number" value="5"/><small>Percentage points</small></div>`:'');if(['basket','green'].includes(marketType))h=`<div class="field"><label>Basket</label><select id="basket"><option>Frontier AI — OPENAI / ANTHROPIC / FIGUREAI</option><option>Future Systems — SPACEX / ANDURIL / NEURALINK</option><option>Prediction Infra — KALSHI / POLYMARKET</option><option>Private Tech 8 — all PreStocks</option></select></div>`+(marketType==='green'?`<div class="field"><label>Minimum green members</label><input id="greenCount" type="number" value="2" min="1" max="8"/></div>`:'');if(marketType==='move')h=`<div class="field"><label>Absolute move threshold</label><input id="movePct" type="number" value="20"/><small>Percent in either direction from launch</small></div>`;if(marketType==='leader')h=`<div class="field"><label>Universe</label><select id="leaderUniverse"><option>All 8 PreStocks</option><option>Frontier AI</option><option>Future Systems</option></select></div>`;if(['pricezone','valuezone'].includes(marketType)){const low=marketType==='pricezone'?(a.tokenPrice*.9).toFixed(2):(a.impliedValuation/1e9*.9).toFixed(1),high=marketType==='pricezone'?(a.tokenPrice*1.1).toFixed(2):(a.impliedValuation/1e9*1.1).toFixed(1);h=`<div class="field"><label>Zone low</label><input id="zoneLow" type="number" step="0.01" value="${low}"/></div><div class="field"><label>Zone high</label><input id="zoneHigh" type="number" step="0.01" value="${high}"/></div>`}if(['gain','shield'].includes(marketType))h=`<div class="field"><label>${marketType==='gain'?'Minimum gain':'Maximum loss'}</label><input id="returnPct" type="number" value="15"/><small>Percent from launch</small></div>`;h+=`<div class="field"><label>Resolution date</label><input id="expiry" type="date" value="2027-06-30"/></div>`;$('#builderFields').innerHTML=h;updatePreview();$$('#builderFields input,#builderFields select').forEach(x=>x.oninput=updatePreview)}
function buildRule(){const a=assets.find(x=>x.symbol===selected), by=Object.fromEntries(assets.map(x=>[x.symbol,x])), other=$('#other')?.value;if(marketType==='threshold')return {type:'valuation_threshold',operator:'gte',target:Number($('#target').value)*1e9,metric:'impliedValuation',launchValue:Number(a.impliedValuation)};if(marketType==='price')return {type:'price_threshold',operator:'gte',target:Number($('#priceTarget').value),metric:'tokenPrice',launchValue:Number(a.tokenPrice)};if(marketType==='premium')return {type:'premium_band',absMaxPct:Number($('#premiumBand').value),metric:'token_vs_mark',launchToken:Number(a.tokenPrice),launchMark:Number(a.markPrice)};if(marketType==='relative')return {type:'relative_return',left:a.symbol,right:other,leftLaunchPrice:Number(a.tokenPrice),rightLaunchPrice:Number(by[other].tokenPrice)};if(marketType==='spread')return {type:'valuation_ratio',left:a.symbol,right:other,launchRatio:Number(a.impliedValuation)/Number(by[other].impliedValuation)};if(marketType==='move')return {type:'absolute_return',absMinPct:Number($('#movePct').value),launchPrice:Number(a.tokenPrice),metric:'tokenPrice'};if(marketType==='leader'){const members=marketType&&($('#leaderUniverse').value.startsWith('Frontier')?['OPENAI','ANTHROPIC','FIGUREAI']:$('#leaderUniverse').value.startsWith('Future')?['SPACEX','ANDURIL','NEURALINK']:assets.map(x=>x.symbol));return {type:'universe_leader',members,candidate:a.symbol,launchPrices:Object.fromEntries(members.map(s=>[s,Number(by[s].tokenPrice)]))}}if(marketType==='pricezone')return {type:'price_zone',low:Number($('#zoneLow').value),high:Number($('#zoneHigh').value),metric:'tokenPrice',launchPrice:Number(a.tokenPrice)};if(marketType==='valuezone')return {type:'valuation_zone',low:Number($('#zoneLow').value)*1e9,high:Number($('#zoneHigh').value)*1e9,metric:'impliedValuation',launchValue:Number(a.impliedValuation)};if(marketType==='gain')return {type:'return_threshold',operator:'gte',thresholdPct:Number($('#returnPct').value),launchPrice:Number(a.tokenPrice)};if(marketType==='shield')return {type:'return_threshold',operator:'gte',thresholdPct:-Number($('#returnPct').value),launchPrice:Number(a.tokenPrice)};if(marketType==='duel')return {type:'relative_margin',left:a.symbol,right:other,marginPct:Number($('#marginPct').value),leftLaunchPrice:Number(a.tokenPrice),rightLaunchPrice:Number(by[other].tokenPrice)};const members=basketMembers($('#basket')?.value),launchPrices=Object.fromEntries(members.map(s=>[s,Number(by[s].tokenPrice)]));if(marketType==='green')return {type:'green_count',members,minimum:Number($('#greenCount').value),launchPrices};return {type:'basket_return_threshold',members,weights:members.map(()=>1/members.length),thresholdPct:0,launchPrices}}
function updatePreview(){$('#marketPreview').innerHTML=`<b>Market contract</b>${marketQuestion()}<br/><small>Fully collateralized participant pool. Automatic settlement rule is stored with the market; Stocklana collects the disclosed protocol fee and does not take a side.</small>`}
function syncType(){$$('.type').forEach(x=>x.classList.toggle('active',x.dataset.type===marketType))}
$$('.type').forEach(b=>b.onclick=()=>{marketType=b.dataset.type;syncType();buildFields()});
$('#createMarketBtn').onclick=async()=>{if(!sessionToken)return toast('Authenticate wallet first');const a=assets.find(x=>x.symbol===selected),payload={underlyingMint:a.contract_address,symbol:a.symbol,question:marketQuestion(),resolveAt:$('#expiry')?.value||'2027-06-30',creator:trader(),feeBps:Number($('#feeBps')?.value||100),pricingMode:'PARIMUTUEL',rule:buildRule()};const r=await fetch('/api/markets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)return toast(j.error||'Market create failed');toast('Market is live and fully collateralized');await loadMarkets();navigate('markets')};
async function trade(mid,side,shares){
 if(trader()==='guest'){toast('Connect wallet first');return}
 const qr=await fetch(`/api/markets/${mid}/quote`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({side,shares})}),q=await qr.json();
 if(!qr.ok)return toast(q.error||'Quote failed');
 if(Number(vault.balances?.USDC||0)>=q.total){
   const r=await fetch(`/api/markets/${mid}/trade`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({side,shares,trader:trader(),paymentMode:'vault'})}),j=await r.json();
   if(!r.ok)return toast(j.error||'Trade failed'); toast(`${side} filled from Stocklana Vault · ${money(j.trade.total)}`); await Promise.all([loadMarkets(),loadVault()]); return;
 }
 if(wallet?.provider&&config.vaultAddress){
   try{toast('Approve the on-chain USDC market payment');const j=await executeChainBackedTrade({provider:wallet.provider,marketId:mid,side,shares,vaultAddress:config.vaultAddress,trader:trader(),usdcMint:config.usdcMint});toast(`${side} settled on Solana · ${short(j.chainProof.signature)}`);await Promise.all([loadMarkets(),loadVault()]);return}catch(e){toast(String(e.message||e));return}
 }
 toast(`Need ${money(q.total)} USDC. Deposit or configure the Stocklana Solana vault.`);navigate('vault')
}
async function loadMarkets(){try{const r=await fetch('/api/markets',{cache:'no-store'});markets=await r.json();renderMarketFeed();renderDesk()}catch(e){console.warn(e)}}
function renderDesk(){const el=$('#portfolioState');if(!markets.length){el.className='empty-card';el.innerHTML='<span>◎</span><h3>No markets yet</h3>';return}const mine=markets.filter(m=>m.creator===trader()||m.trades?.some(t=>t.trader===trader()));el.className='market-board';el.innerHTML=(mine.length?mine:markets.slice(0,8)).map(m=>{const y=Math.round((m.yesProbability??.5)*100);return `<article class="market-card" data-mid="${m.id}"><span class="status-pill">${m.status}</span><h3>${m.question}</h3><div class="prob-row"><div class="prob yes"><small>YES</small><b>${y}¢</b></div><div class="prob no"><small>NO</small><b>${100-y}¢</b></div></div><small>${m.symbol} · ${money(m.volume||0)} volume · ${m.trades?.length||0} trades</small>${m.status==='OPEN'?`<div class="trade-row"><input type="number" min="1" value="10" class="shares"/><button class="primary buy" data-side="YES">Buy YES</button><button class="ghost buy" data-side="NO">Buy NO</button></div>`:`<div class="market-actions"><b>Resolved ${m.outcome}</b><button class="primary redeem">Redeem</button></div>`}</article>`}).join('');el.querySelectorAll('.market-card').forEach(card=>{const mid=card.dataset.mid;card.querySelectorAll('.buy').forEach(b=>b.onclick=()=>trade(mid,b.dataset.side,Number(card.querySelector('.shares').value)));card.querySelector('.redeem')?.addEventListener('click',()=>redeem(mid))})}
async function redeem(mid){const r=await fetch(`/api/markets/${mid}/redeem`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trader:trader()})}),j=await r.json();if(!r.ok)return toast(j.error||'Redeem failed');toast(`Redeemed ${money(j.payout)} to vault`);await loadVault()}
async function loadVault(){if(trader()==='guest'){$('#vaultBalance').textContent='$0.00';$('#vaultIdentity').textContent='Connect a wallet to activate your vault';return}try{const [a,p,r]=await Promise.all([fetch(`/api/vault?trader=${encodeURIComponent(trader())}`).then(x=>x.json()),fetch(`/api/positions?trader=${encodeURIComponent(trader())}`).then(x=>x.json()),fetch('/api/receipts?limit=20').then(x=>x.json())]);vault=a;positions=p;$('#vaultBalance').textContent=money(a.balances?.USDC||0);$('#vaultIdentity').textContent=short(trader());$('#cashPocket').textContent=money(a.subaccounts?.CASH?.USDC||0);$('#tradingPocket').textContent=money(a.subaccounts?.TRADING?.USDC||0);$('#reservePocket').textContent=money(a.subaccounts?.RESERVE?.USDC||0);$('#vaultPositions').innerHTML=p.length?p.map(x=>`<div class="position-row" data-mid="${x.marketId}"><h4>${x.symbol||''} · ${x.status||''}</h4><small>${x.question||x.marketId}</small><div>YES <b>${Number(x.yes||0).toFixed(2)}</b> · NO <b>${Number(x.no||0).toFixed(2)}</b></div><button class="mini send-pos">Send position</button></div>`).join(''):'<div class="position-row"><small>No positions yet.</small></div>';$$('.send-pos').forEach(b=>b.onclick=()=>sendPosition(b.closest('[data-mid]').dataset.mid));$('#receiptList').innerHTML=(r.receipts||[]).slice(0,12).map(x=>`<div class="receipt-row"><b>${x.kind.replaceAll('_',' ')}</b><small>${new Date(x.at).toLocaleString()}</small><code>${x.commitment?`${x.commitment.slice(0,12)}…`:''}</code></div>`).join('')||'<div class="receipt-row"><small>No receipts yet.</small></div>'}catch(e){toast('Vault unavailable')}}
async function sendPosition(mid){const p=positions.find(x=>x.marketId===mid);if(!p)return;const side=String(prompt('Send YES or NO?','YES')||'').toUpperCase();if(!['YES','NO'].includes(side))return;const max=side==='YES'?p.yes:p.no, shares=Number(prompt(`Shares to send (max ${max})`,String(Math.min(1,max)))||0), recipient=prompt('Recipient Stocklana identity / Solana address');if(!recipient||shares<=0)return;const r=await fetch(`/api/markets/${mid}/transfer-position`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trader:trader(),recipient,side,shares})}),j=await r.json();if(!r.ok)return toast(j.error||'Transfer failed');toast('Position transferred');loadVault()}
$('#withdrawBtn').onclick=async()=>{if(trader()==='guest')return toast('Connect wallet first');const destination=prompt('Solana wallet to receive USDC',trader()),amount=Number(prompt('USDC to withdraw','25')||0);if(!destination||amount<=0)return;const r=await fetch('/api/vault/withdraw',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trader:trader(),destination,amount,asset:'USDC'})}),j=await r.json();if(!r.ok)return toast(j.error||'Withdrawal request failed');toast(`Withdrawal reserved · ${j.withdrawal.id.slice(0,10)}…`);await loadVault()};
$('#sendMoneyBtn').onclick=async()=>{if(trader()==='guest')return toast('Connect wallet first');const recipient=prompt('Recipient Stocklana identity / Solana address'),amount=Number(prompt('USDC amount','10')||0);if(!recipient||amount<=0)return;const r=await fetch('/api/vault/transfer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trader:trader(),recipient,amount,asset:'USDC'})}),j=await r.json();if(!r.ok)return toast(j.error||'Transfer failed');toast('Internal transfer settled');loadVault()};
async function movePocket(destination){if(trader()==='guest')return toast('Connect wallet first');const source=destination==='TRADING'?'CASH':'CASH',amount=Number(prompt(`USDC to move into ${destination}`,'25')||0);if(amount<=0)return;const r=await fetch('/api/vault/move',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trader:trader(),source,destination,amount,asset:'USDC'})}),j=await r.json();if(!r.ok)return toast(j.error||'Pocket move failed');toast(`Moved ${money(amount)} to ${destination}`);loadVault()}
$('#moveTradingBtn').onclick=()=>movePocket('TRADING');$('#moveReserveBtn').onclick=()=>movePocket('RESERVE');
$('#fundCardBtn').onclick=async()=>{if(trader()==='guest')return toast('Connect wallet first');const amount=Number(prompt('USD amount to onramp','100')||0);if(amount<=0)return;const providers=await fetch('/api/funding/providers').then(x=>x.json()),provider=providers.providers.find(x=>x.ready&&['stripe','coinbase'].includes(x.id));if(!provider)return toast('Card onramp adapter needs provider URL configuration');const r=await fetch('/api/funding/onramp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trader:trader(),provider:provider.id,amount})}),j=await r.json();if(j.url)window.open(j.url,'_blank');else toast(j.reason||'Onramp unavailable')};
$('#fundWalletBtn').onclick=async()=>{if(!wallet?.provider)return toast('Connect wallet first');if(!config.vaultAddress)return toast('Set STOCKLANA_VAULT_ADDRESS on the server');const amount=Number(prompt('USDC to deposit from wallet','25')||0);if(amount<=0)return;try{toast('Approve USDC transfer in wallet');const signature=await sendSplToken({provider:wallet.provider,to:config.vaultAddress,mint:config.usdcMint,amount});const r=await fetch('/api/vault/confirm-deposit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trader:trader(),wallet:trader(),amount,signature})}),j=await r.json();if(!r.ok)throw new Error(j.error||'verification_failed');toast(`Verified ${money(j.chainProof.verifiedAmount)} deposit`);loadVault()}catch(e){toast(String(e.message||e))}};
$$('[data-launch]').forEach(b=>b.onclick=()=>{const kind=b.dataset.launch;$('#launchDialogContent').innerHTML=kind==='sponsored'?'<span class="kicker">SPONSORED ROUTER</span><h2>Search free rails first</h2><p>Sponsored venues are checked before user-paid launch routes.</p>':kind==='native'?'<span class="kicker">STOCKLANA NATIVE</span><h2>Native launch path</h2><p>Service fee: <b>0.005 ETH</b>. Network and pool costs remain separate.</p>':'<span class="kicker">OPTIONAL ADAPTER</span><h2>Clawpump compatibility</h2><p>Kept outside the core market and vault architecture.</p>';$('#launchDialog').showModal()});
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
async function connectPrimaryWallet(){try{wallet=await connectSolanaWallet();await authenticateWallet(wallet);$('#walletBtn').textContent=short(wallet.publicKey);$('#walletBtn').classList.add('connected');toast('Wallet authenticated');await Promise.all([loadVault(),loadWalletCenter(),loadV2Home()]);return wallet}catch(e){toast(e.message==='solana_wallet_not_found'?'Install or open Phantom to connect your Solana wallet':'Wallet connection failed');throw e}}
$('#walletBtn').onclick=async()=>{if(wallet?.publicKey){navigate('wallet');return}try{await connectPrimaryWallet();navigate('wallet')}catch{}};
$('#refreshBtn').onclick=loadLive;async function loadLive(){try{const r=await fetch('/api/prestocks',{cache:'no-store'}),j=await r.json();if(Array.isArray(j)&&j.length){assets=j.map((x,i)=>({...fallback.find(f=>f.symbol===x.symbol),...x}));renderAssets();toast('Live PreStocks refreshed')}}catch{toast('Using PreStocks snapshot')}}
async function scheduleRecurring(a){if(!sessionToken)return toast('Authenticate wallet first');const amount=Number(prompt(`USDC per recurring ${a.symbol} buy`,'25')||0),cadence=(prompt('Cadence: DAILY, WEEKLY, MONTHLY','WEEKLY')||'WEEKLY').toUpperCase();if(amount<=0)return;const r=await fetch('/api/equity/recurring',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({symbol:a.symbol,usdcAmount:amount,cadence})}),j=await r.json();toast(r.ok?`${cadence} ${a.symbol} plan created`:(j.error||'Plan failed'))}
async function shareSignal(a){if(!sessionToken)return toast('Authenticate wallet first');const thesis=prompt(`Your ${a.symbol} thesis`,'')||'';if(!thesis)return;const r=await fetch('/api/equity/social',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({symbol:a.symbol,thesis,visibility:'FRIENDS'})}),j=await r.json();toast(r.ok?'Copyable equity thesis created':(j.error||'Signal failed'))}
async function buyUnderlying(a){if(!sessionToken||!wallet?.provider)return toast('Authenticate wallet first');const usdc=Number(prompt(`USDC to exchange for ${a.symbol}`,'25')||0);if(usdc<=0)return;try{toast('Building Jupiter order');const r=await fetch('/api/prestocks/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mint:a.contract_address,side:'BUY',usdcAmount:usdc})}),o=await r.json();if(!r.ok)throw new Error(o.error||'order_failed');if(!o.ready)return toast(o.reason||'Jupiter connector not configured');toast('Approve the PreStocks swap');const signedTransaction=await signSerializedTransaction({provider:wallet.provider,transactionBase64:o.transaction});const er=await fetch('/api/prestocks/execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({signedTransaction,requestId:o.requestId})}),ej=await er.json();if(!er.ok)throw new Error(ej.error||'execution_failed');toast(`Underlying executed · ${short(ej.signature||ej.txid||ej.status)}`);$('#assetDialog').close()}catch(e){toast(String(e.message||e))}}
async function loadAgents(){const g=$('#agentGrid');if(!g)return;try{const d=await fetch('/api/agent-vaults').then(r=>r.json());g.innerHTML=d.vaults.slice(0,100).map(v=>`<article class="asset-card"><div class="asset-head"><span class="status live">${v.status}</span><span class="sym">${v.crypto}</span></div><h3>${v.name}</h3><small>${v.agentId}</small><div class="market-chips">${v.connectors.map(x=>`<span>${x}</span>`).join('')}</div><div class="valuation">Daily ${money(v.policy.dailySpendLimitUSDC)} · human gate ${money(v.policy.humanApprovalAboveUSDC)}</div><small>${Object.values(v.financialTokens||{}).flat?.().filter?.(x=>typeof x==='string').slice(0,5).join(' · ')||'SL-AGENT · SL-CASH · SL-POS'}</small></article>`).join('');$('#agentWeekMetrics').innerHTML=`<div><b>${d.count}</b><span>Agent Vaults</span></div><div><b>700</b><span>Week sessions</span></div><div><b>100%</b><span>Scoped identities</span></div>`}catch(e){g.innerHTML='<div class="empty-card">Agent proof unavailable</div>'}}
document.querySelectorAll('[data-nav="agents"]').forEach(b=>b.addEventListener('click',loadAgents));$('#agentRefresh')?.addEventListener('click',loadAgents);
let lastCardPolicy=null;
$('#singleUseCardBtn')?.addEventListener('click',async()=>{if(!sessionToken)return toast('Authenticate wallet first');const amount=Number(prompt('Maximum USDC value for this one-time card','25')||0),merchant=prompt('Merchant restriction (optional)','')||null,mcc=prompt('MCC restriction (optional)','')||null;if(amount<=0)return;const r=await fetch('/api/card/policy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,merchant,mcc,ttl:900})}),j=await r.json();if(!r.ok)return toast(j.error||'Policy failed');lastCardPolicy=j.id;toast(`Reserved ${money(j.maxAmountUSDC)} for one purchase`) });
$('#issueVirtualCardBtn')?.addEventListener('click',async()=>{if(!lastCardPolicy)return toast('Create a one-time spend policy first');const r=await fetch('/api/card/issue',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({policyId:lastCardPolicy})}),j=await r.json();if(!r.ok)return toast(j.error||'Issuance failed');toast(j.ready?'Provider virtual card issued':'Issuer credentials are not configured on this deployment')});
$('#maqueSendBtn')?.addEventListener('click',async()=>{if(!sessionToken)return toast('Authenticate wallet first');const to=prompt('Send to @handle or Stocklana identity','@friend'),amount=Number(prompt('USDC amount','10')||0);if(!to||amount<=0)return;const r=await fetch('/api/pay/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({to,amount,asset:'USDC',memo:'MAQUE payment'})}),j=await r.json();toast(r.ok?'MAQUE payment settled':(j.error||'Payment failed'));if(r.ok)loadVault()});
$('#maqueRequestBtn')?.addEventListener('click',async()=>{if(!sessionToken)return toast('Authenticate wallet first');const amount=Number(prompt('USDC to request','10')||0);if(amount<=0)return;const r=await fetch('/api/pay/request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({payee:trader(),amount,asset:'USDC',memo:'Stocklana request'})}),j=await r.json();if(!r.ok)return toast(j.error||'Request failed');navigator.clipboard?.writeText(j.transport.qr);toast('Payment request copied')});
$('#maqueCashoutBtn')?.addEventListener('click',async()=>{if(!sessionToken)return toast('Authenticate wallet first');const amount=Number(prompt('USDC value to route out','25')||0),destinationType=prompt('Destination type: debit_card, bank, solana','debit_card')||'debit_card',destinationRef=prompt('Destination reference/token','')||'';if(amount<=0)return;const r=await fetch('/api/pay/cashout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,destinationType,destinationRef})}),j=await r.json();toast(r.ok?`Cash-out intent ${j.id} authorized`:(j.error||'Cash-out failed'))});


async function loadWalletCenter(){
  const info=detectSolanaWalletProvider();
  const label=$('#walletProviderLabel'),addr=$('#walletAddressFull'),state=$('#walletSessionState');
  if(label)label.textContent=info.name+(info.available?' · detected':'');
  if(!wallet?.publicKey){
    if(addr)addr.textContent='Not connected';
    if(state)state.textContent=info.available?'Phantom detected. Connect to bring the wallet into Stocklana.':'Phantom is not detected in this browser.';
    ['#walletSolBalance','#walletUsdcBalance','#walletPrestockCount','#walletVaultBalance'].forEach(id=>{const e=$(id);if(e)e.textContent='—'});
    const h=$('#walletPrestockHoldings');if(h)h.innerHTML='<div class="empty-card">Connect Phantom to read holdings.</div>';
    return;
  }
  if(addr)addr.textContent=wallet.publicKey;
  if(state)state.textContent=sessionToken?'Authenticated · wallet signatures stay local':'Connected · authentication pending';
  try{
    const [portfolio,v]=await Promise.all([
      readWalletPortfolio({owner:wallet.publicKey,rpc:config.rpcUrl||'https://api.mainnet-beta.solana.com',usdcMint:config.usdcMint,prestocks:assets}),
      sessionToken?fetch('/api/vault?trader='+encodeURIComponent(trader())).then(r=>r.json()).catch(()=>null):Promise.resolve(null)
    ]);
    lastWalletPortfolio=portfolio;
    $('#walletSolBalance').textContent=Number(portfolio.sol).toLocaleString(undefined,{maximumFractionDigits:4});
    $('#walletUsdcBalance').textContent=money(portfolio.usdc);
    $('#walletPrestockCount').textContent=String(portfolio.prestocks.length);
    $('#walletVaultBalance').textContent=money(v?.balances?.USDC||0);
    const h=$('#walletPrestockHoldings');
    if(h)h.innerHTML=portfolio.prestocks.length?portfolio.prestocks.map(x=>`<button class="wallet-holding" data-wallet-asset="${x.symbol}"><img src="${x.image||''}" alt=""><div><b>${x.name.replace(' PreStocks','')}</b><small>${x.symbol} · ${x.amount.toLocaleString(undefined,{maximumFractionDigits:6})} tokens</small></div><strong>${money(x.estimatedValueUSDC)}</strong></button>`).join(''):'<div class="empty-card">No eligible PreStocks found in this wallet yet.</div>';
    $$('[data-wallet-asset]').forEach(b=>b.onclick=()=>openAsset(b.dataset.walletAsset));
  }catch(e){
    if(state)state.textContent='Connected · wallet balances temporarily unavailable';
    const h=$('#walletPrestockHoldings');if(h)h.innerHTML='<div class="empty-card">Could not read Solana token accounts. Your wallet remains connected.</div>';
  }
}
async function executeWalletSwap(){
 if(!wallet?.provider||!sessionToken){toast('Connect Phantom first');return}
 const from=$('#swapFrom')?.value||'SOL', target=$('#swapTo')?.value||config.usdcMint, amount=Number($('#swapAmount')?.value||0);
 if(amount<=0){toast('Enter an amount to convert');return}
 const inputMint=from==='SOL'?'So11111111111111111111111111111111111111112':config.usdcMint;
 const outputMint=target==='USDC'?config.usdcMint:target;
 const decimals=from==='SOL'?9:6, amountAtomic=Math.round(amount*10**decimals);
 try{
   toast('Building the best Solana route');
   const r=await fetch('/api/swap/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({inputMint,outputMint,amountAtomic})});
   const o=await r.json();if(!r.ok)throw new Error(o.error||'swap_route_failed');if(!o.ready)throw new Error(o.reason||'Jupiter connector not configured');
   toast('Approve the conversion in Phantom');
   const signedTransaction=await signSerializedTransaction({provider:wallet.provider,transactionBase64:o.transaction});
   const er=await fetch('/api/swap/execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({signedTransaction,requestId:o.requestId})});
   const ej=await er.json();if(!er.ok)throw new Error(ej.error||'swap_execution_failed');
   toast(`Converted on Solana · ${short(ej.signature||ej.txid||ej.status)}`);await loadWalletCenter();
 }catch(e){toast(String(e.message||e))}
}
async function loadCommerce(){
 const h=$('#commerceHistory');if(!h)return;
 if(!sessionToken){h.innerHTML='<div class="empty-card">Connect Phantom to create wallet-backed purchases.</div>';return}
 try{
   const d=await fetch('/api/commerce/intents',{cache:'no-store'}).then(r=>r.json());
   h.innerHTML=(d.intents||[]).length?(d.intents||[]).slice(0,10).map(x=>`<div class="commerce-row"><b>${x.merchant||x.merchantHost} · ${money(x.maxAmountUSDC)}</b><small>${x.status} · ${x.agentId?'Agent '+x.agentId:'Human'} · ${x.fundingSource}</small></div>`).join(''):'<div class="empty-card">No purchase intents yet.</div>';
 }catch{h.innerHTML='<div class="empty-card">Commerce history unavailable.</div>'}
}
function renderCommerceResult(out){
 const el=$('#commerceResult');if(!el)return;
 const intent=out.intent||out, issuance=out.issuance||{};
 if(out.requiresWalletTransfer){el.innerHTML=`<div class="commerce-warning"><b>Ready for wallet funding</b><p>Approve ${money(intent.maxAmountUSDC)} USDC from Phantom. Stocklana verifies the Solana transfer before reserving the one-time purchase.</p></div>`;return}
 const ready=!!issuance.ready;
 el.innerHTML=`<div class="${ready?'commerce-success':'commerce-warning'}"><b>${ready?'Purchase rail ready':'Purchase policy reserved'}</b><p>${ready?'The one-time merchant-bound payment rail is ready.':'The Stocklana policy is real, but this deployment still needs the external card issuer connector before it can be used at ordinary web checkout.'}</p>${ready&&issuance.hostedRevealUrl?`<a class="primary" href="${issuance.hostedRevealUrl}" target="_blank" rel="noopener">Open secure card</a>`:''} ${ready&&issuance.walletPassUrl?`<a class="ghost" href="${issuance.walletPassUrl}" target="_blank" rel="noopener">Add to wallet</a>`:''} <a class="ghost" href="${intent.merchantUrl}" target="_blank" rel="noopener">Open merchant</a></div>`;
}
async function createCommercePurchase(){
 if(!wallet?.provider||!sessionToken){toast('Connect Phantom first');return}
 const merchantUrl=$('#commerceUrl')?.value?.trim(),amount=Number($('#commerceAmount')?.value||0),fundingSource=$('#commerceFunding')?.value||'WALLET_USDC',agentId=$('#commerceAgent')?.value?.trim()||null;
 if(!merchantUrl||amount<=0){toast('Add a merchant URL and maximum spend');return}
 try{
   const r=await fetch('/api/commerce/intents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({merchantUrl,amount,fundingSource,agentId,allowSubscriptions:false,approvalAbove:amount,note:'Stocklana web purchase'})});
   let out=await r.json();if(!r.ok)throw new Error(out.error||'purchase_intent_failed');
   renderCommerceResult(out);
   if(out.requiresWalletTransfer){
     if(!config.vaultAddress)throw new Error('stocklana_vault_not_configured');
     toast(`Approve ${money(amount)} USDC in Phantom`);
     const signature=await sendSplToken({provider:wallet.provider,to:config.vaultAddress,mint:config.usdcMint,amount,decimals:6,rpc:config.rpcUrl});
     const fr=await fetch('/api/commerce/fund-wallet',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intentId:out.intent.id,signature,wallet:wallet.publicKey})});
     out=await fr.json();if(!fr.ok)throw new Error(out.error||'purchase_funding_failed');renderCommerceResult(out);
   }
   toast((out.issuance||{}).ready?'Safe purchase ready':'Purchase policy created');await Promise.all([loadCommerce(),loadVault(),loadWalletCenter()]);
 }catch(e){toast(String(e.message||e))}
}
$('#swapExecuteBtn')?.addEventListener('click',executeWalletSwap);
$('#walletSwapBtn')?.addEventListener('click',()=>$('#swapAmount')?.focus());
$('#walletShopBtn')?.addEventListener('click',()=>navigate('commerce'));
$('#commerceCreateBtn')?.addEventListener('click',createCommercePurchase);
$('#commerceUrl')?.addEventListener('input',e=>{try{$('#commerceMerchantRule').textContent=new URL(e.target.value).hostname||'Locked to URL'}catch{$('#commerceMerchantRule').textContent='Locked to URL'}});
$('#walletConnectCenterBtn')?.addEventListener('click',async()=>{try{await connectPrimaryWallet()}catch{}});
$('#walletRefreshBtn')?.addEventListener('click',loadWalletCenter);
$('#walletCopyBtn')?.addEventListener('click',async()=>{if(!wallet?.publicKey)return toast('Connect Phantom first');await navigator.clipboard?.writeText(wallet.publicKey);toast('Wallet address copied')});
$('#walletExplorerBtn')?.addEventListener('click',()=>{if(!wallet?.publicKey)return toast('Connect Phantom first');window.open(`https://solscan.io/account/${wallet.publicKey}`,'_blank','noopener')});
$('#walletBuyPrestockBtn')?.addEventListener('click',()=>navigate('markets'));
$('#walletDepositCenterBtn')?.addEventListener('click',()=>{navigate('vault');setTimeout(()=>$('#fundWalletBtn')?.focus(),250)});
$('#walletSendCenterBtn')?.addEventListener('click',()=>{navigate('vault');setTimeout(()=>$('#maqueSendBtn')?.focus(),250)});
$$('[data-wallet-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.walletRoute)));
onWalletAccountChanged(async pk=>{sessionToken=null;if(!pk){wallet=null;$('#walletBtn').textContent='Connect wallet';$('#walletBtn').classList.remove('connected');await loadWalletCenter();await loadV2Home();return}try{wallet=await connectSolanaWallet();await authenticateWallet(wallet);$('#walletBtn').textContent=short(wallet.publicKey);$('#walletBtn').classList.add('connected');await Promise.all([loadWalletCenter(),loadVault(),loadV2Home()])}catch{}});

async function loadV2Home(){
  const homeAssets=$('#homeAssets');
  try{
    const d=await fetch('/api/v2/home',{cache:'no-store'}).then(r=>r.json());
    const list=(d.equities||assets).slice(0,3);
    if(homeAssets)homeAssets.innerHTML=list.map(a=>`<button class="home-equity" data-home-asset="${a.symbol}"><div class="home-equity-head"><img src="${a.image||''}" alt=""><span class="status live">24/7</span></div><b>${a.name.replace(' PreStocks','')}</b><small>${a.symbol}</small><div class="eq-price">${money(a.tokenPrice)}</div><small>Use it →</small></button>`).join('');
    $$('[data-home-asset]').forEach(b=>b.onclick=()=>openAsset(b.dataset.homeAsset));
    const ac=d.account;if(ac){const cash=Number(ac.balances?.USDC||0);$('#homeCash').textContent=money(cash);$('#homeNetValue').textContent=money(cash);$('#homePositions').textContent=String(ac.positions||0);$('#homeAccountState').textContent='ACTIVE';$('#homeAccountState').className='status live'}else{$('#homeAccountState').textContent='CONNECT TO ACTIVATE'}
  }catch(e){if(homeAssets)homeAssets.innerHTML='<div class="empty-card">Live account summary unavailable</div>'}
}
async function loadCredit(){
  if(!$('#creditPower'))return;
  if(!sessionToken){$('#creditPower').textContent='Connect to calculate';return}
  try{const d=await fetch('/api/accounting/me').then(r=>r.json());const spend=Number(d?.monetary?.spendableUSDC||d?.spendableUSDC||0),coll=Number(d?.collateral?.totalUSDC||d?.collateralUSDC||0);$('#creditPower').textContent=money(Math.max(coll*.5,spend*.25))}catch{$('#creditPower').textContent='Check provider routes'}
}
function requireWalletAction(fn){if(!wallet||!sessionToken){toast('Connect and authenticate your Solana wallet first');return false}fn?.();return true}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{
 const a=b.dataset.action;
 if(a==='buy')navigate('markets');
 if(a==='auto'){navigate('markets');toast('Choose an equity, then tap Auto')}
 if(a==='borrow')navigate('credit');
 if(a==='play')navigate('lab');
 if(a==='send'){navigate('vault');setTimeout(()=>$('#maqueSendBtn')?.focus(),250)}
 if(a==='spend'){navigate('commerce');setTimeout(()=>$('#commerceUrl')?.focus(),250)}
 if(a==='agent')navigate('agents');
 if(a==='launch')navigate('launch');
 if(a==='add-money'){navigate('vault');setTimeout(()=>$('#fundCardBtn')?.focus(),250)}
}));
$('#creditStartBtn')?.addEventListener('click',()=>requireWalletAction(loadCredit));
$('#internalBorrowBtn')?.addEventListener('click',async()=>{if(!requireWalletAction())return;const collateral=Number(prompt('Collateral value in USDC','250')||0),borrow=Number(prompt('Amount to borrow in USDC','100')||0);if(collateral<=0||borrow<=0)return;try{const q=await fetch('/api/lending/quote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({collateral,borrow,days:30})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'quote_failed');return j});if(confirm(`30-day quote: borrow ${money(borrow)} against ${money(collateral)}. Open funded loan?`)){const r=await fetch('/api/lending/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({collateral,borrow,days:30})}),j=await r.json();toast(r.ok?`Credit opened · ${j.loanId||'funded'}`:(j.error||'Credit route unavailable'));await loadCredit()}}catch(e){toast(String(e.message||e))}});
$('#kaminoBorrowBtn')?.addEventListener('click',async()=>{if(!requireWalletAction())return;const market=prompt('Kamino market address','')||'',reserve=prompt('Supported collateral reserve address','')||'',amount=prompt('Atomic deposit amount','')||'';if(!market||!reserve||!amount)return;try{const r=await fetch('/api/kamino/deposit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({wallet:wallet.publicKey,market,reserve,amount})}),j=await r.json();if(!r.ok)throw new Error(j.error||'kamino_builder_failed');toast('Kamino transaction built — sign locally in wallet')}catch(e){toast(String(e.message||e))}});

function ambient(){const c=$('#ambient'),x=c.getContext('2d');let w,h,d=1;function size(){d=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*d;c.height=h*d;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(d,0,0,d,0,0)}function draw(t){x.clearRect(0,0,w,h);x.strokeStyle='rgba(110,180,230,.055)';x.lineWidth=1;const s=44;for(let i=-s;i<w+s;i+=s){x.beginPath();x.moveTo(i+(t*.003)%s,0);x.lineTo(i-140+(t*.003)%s,h);x.stroke()}for(let y=40;y<h;y+=s){x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}requestAnimationFrame(draw)}addEventListener('resize',size);size();requestAnimationFrame(draw)}
(async()=>{ambient();renderAssets();buildFields();loadV2Home();config=await fetch('/api/config').then(r=>r.json()).catch(()=>({}));refreshSwapTargets();await loadLive();await loadMarkets();const s=await walletState();if(s.publicKey){wallet=await connectSolanaWallet().catch(()=>null);if(wallet){await authenticateWallet(wallet).catch(()=>{});$('#walletBtn').textContent=short(s.publicKey);$('#walletBtn').classList.add('connected');if(sessionToken)await loadVault();await loadWalletCenter()}}})();

async function loadCoverage(){
  const grid=document.querySelector('#coverageGrid'); if(!grid)return;
  try{
    const data=await fetch('/api/track-fit',{cache:'no-store'}).then(r=>r.json());
    const entries=Object.entries(data).filter(([k])=>k!=='wedge');
    grid.innerHTML=`<article class="route"><div class="route-top"><span class="status live">WEDGE</span><b>ONE PRODUCT</b></div><h3>Programmable tokenized-equity ownership</h3><p>${data.wedge}</p></article>`+entries.map(([k,v])=>`<article class="asset-card"><div class="asset-head"><span class="status">2×</span><span class="sym">${k.replaceAll('_',' ').toUpperCase()}</span></div><h3>${k.replaceAll('_',' ')}</h3><div class="market-chips">${v.map(x=>`<span>${x}</span>`).join('')}</div></article>`).join('');
  }catch(e){grid.innerHTML='<div class="empty-card">Track-fit matrix unavailable</div>'}
}
document.querySelectorAll('[data-nav="coverage"]').forEach(b=>b.addEventListener('click',loadCoverage));
document.querySelector('#coverageRefresh')?.addEventListener('click',loadCoverage);
document.querySelectorAll('[data-nav="infrastructure"]').forEach(b=>b.addEventListener('click',async()=>{try{await fetch('/api/iso20022').then(r=>r.json());const a=await fetch('/api/accounting/tokens',{cache:'no-store'}).then(r=>r.json());const i=a.invariants||{};const c=document.querySelector('#acctCoverage'),p=document.querySelector('#acctProof');if(c)c.textContent=(i.cashCoverageRatio==null?'N/A':`${i.cashCoverageRatio.toFixed(4)}×`);if(p)p.textContent=`USDC ${Number(i.externalUSDC||0).toFixed(2)} · claims ${Number(i.monetaryClaimsUSDC||0).toFixed(2)} · journal ${i.journalBalanced?'balanced':'ERROR'} · ${i.fullyBackedMonetaryClaims?'fully backed':'UNDERBACKED'}.`;}catch(e){const p=document.querySelector('#acctProof');if(p)p.textContent='Accounting proof unavailable.';}}));



// ---- Stocklana Launch Exchange / Pons v2 Robinhood Chain ----
let evmAccount=null, ponsConfig=null;
const launchKey='stocklana:pons:v2:tracked';
const trackedLaunches=()=>{try{return JSON.parse(localStorage.getItem(launchKey)||'[]')}catch{return []}};
const saveTracked=(addr)=>{const a=String(addr||'').trim();if(!/^0x[a-fA-F0-9]{40}$/.test(a))return false;const xs=[a,...trackedLaunches().filter(x=>x.toLowerCase()!=a.toLowerCase())].slice(0,50);localStorage.setItem(launchKey,JSON.stringify(xs));return true};
function launchTab(name){document.querySelectorAll('[data-launch-tab]').forEach(b=>b.classList.toggle('active',b.dataset.launchTab===name));document.querySelectorAll('.launch-pane').forEach(p=>p.classList.toggle('active',p.id===`launch-pane-${name}`));if(name==='portfolio')loadPonsPortfolio()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-launch-tab]');if(b)launchTab(b.dataset.launchTab)});
function ponsCard(s){const c=s.curveState,p=Math.max(0,Math.min(100,Number(c?.progress||0))),phase=s.phaseLabel||'Unknown';return `<article class="pons-card" data-pons-token="${s.token}"><div class="pons-card-head"><div><span class="status ${s.phase===0?'live':'neutral'}">${phase.toUpperCase()}</span><h3>${s.name} <small>${s.symbol}</small></h3><code>${short(s.token)}</code></div><b>${s.pairSymbol}</b></div>${c?`<div class="curve-progress"><i style="width:${p}%"></i></div><small>${p.toFixed(2)}% to graduation · ${Number(c.raisedEth).toFixed(4)} / ${Number(c.thresholdEth).toFixed(4)} ${s.pairSymbol}</small><div class="curve-row"><div><span>Trade fee</span><b>${(c.feeBps/100).toFixed(2)}%</b></div><div><span>Creator tax</span><b>${(c.creatorTaxBps/100).toFixed(2)}%</b></div><div><span>Buyback</span><b>${s.buybackEnabled?'ON':'OFF'}</b></div></div>`:`<div class="curve-row"><div><span>Phase</span><b>${phase}</b></div><div><span>Pair</span><b>${s.pairSymbol}</b></div><div><span>Tax</span><b>${(s.creatorTaxBps/100).toFixed(2)}%</b></div></div>`}<div class="pons-actions">${s.phase===0&&s.pairSymbol==='ETH'?`<button class="primary" data-pons-buy="${s.token}">Buy</button><button class="ghost" data-pons-sell="${s.token}">Sell</button>`:''}<button class="ghost wide" data-pons-explorer="${s.explorer}">Open chain proof</button></div></article>`}
async function loadPonsPortfolio(){const g=$('#ponsLaunchGrid');if(!g)return;const list=trackedLaunches();$('#launchCount').textContent=String(list.length);if(!list.length)return;g.innerHTML='<div class="empty-card">Reading live launch state from Robinhood Chain…</div>';const rows=[];for(const token of list){try{rows.push(await readPonsLaunch(token))}catch(e){rows.push({token,name:'Unreadable launch',symbol:'?',phase:9,phaseLabel:String(e.message||e),pairSymbol:'?',creatorTaxBps:0,buybackEnabled:false,explorer:`${PONS_V2.explorer}/token/${token}`})}}g.innerHTML=rows.map(ponsCard).join('')}
async function loadPonsFactory(){ponsConfig=await getPonsConfig();const sel=$('#ponsLaunchConfig');if(sel){sel.innerHTML=ponsConfig.configs.map(c=>`<option value="${c.id}">Config ${c.id} · ${(c.curveFeeBps/100).toFixed(2)}% curve · ${Number(BigInt(c.graduationThreshold))/1e18} quote graduation</option>`).join('')||'<option>No enabled launch configs</option>'}const {formatEther}=await import('https://esm.sh/viem@2.37.9');$('#ponsLaunchFee').textContent=`${formatEther(BigInt(ponsConfig.launchFeeWei))} ETH`;$('#ponsLaunchEligibility').textContent=`Factory live · creator tax cap ${(ponsConfig.maxCreatorTaxBps/100).toFixed(2)}%`}
$('#connectEvmBtn')?.addEventListener('click',async()=>{try{const x=await connectRobinhood();evmAccount=x.address;$('#connectEvmBtn').textContent=short(evmAccount);$('#connectEvmBtn').classList.add('connected');await loadPonsFactory();toast('Robinhood Chain wallet connected')}catch(e){toast(e.message==='evm_wallet_not_found'?'Open an EVM wallet such as MetaMask or Robinhood Wallet':String(e.message||e))}});
$('#ponsPairMode')?.addEventListener('change',e=>{$('#ponsPairAddressField').hidden=e.target.value!=='CUSTOM'});
$('#ponsImportBtn')?.addEventListener('click',async()=>{const addr=$('#ponsImportAddress').value.trim(),out=$('#ponsImportResult');if(!/^0x[a-fA-F0-9]{40}$/.test(addr)){toast('Enter the full 0x token address');return}out.innerHTML='<div class="empty-card">Reading factory and curve…</div>';try{const s=await readPonsLaunch(addr);saveTracked(addr);out.innerHTML=ponsCard(s);toast(`${s.symbol} imported from chain`);$('#launchCount').textContent=trackedLaunches().length}catch(e){out.innerHTML=`<div class="warn">${String(e.message||e)}</div>`}});
$('#ponsLaunchBtn')?.addEventListener('click',async()=>{try{if(!evmAccount){const x=await connectRobinhood();evmAccount=x.address}if(!ponsConfig)await loadPonsFactory();const name=$('#ponsName').value.trim(),symbol=$('#ponsSymbol').value.trim();if(!name||!symbol)throw new Error('name_and_symbol_required');const pairMode=$('#ponsPairMode').value,pairToken=pairMode==='CUSTOM'?$('#ponsPairToken').value.trim():'';const input={name,symbol,pairToken,launchConfigId:Number($('#ponsLaunchConfig').value||0),creatorTaxBps:Math.round(Number($('#ponsCreatorTax').value||0)*100),buybackEnabled:$('#ponsBuyback').checked,logo:$('#ponsLogo').value.trim(),description:$('#ponsDescription').value.trim(),website:$('#ponsWebsite').value.trim(),twitter:$('#ponsTwitter').value.trim(),farcaster:$('#ponsFarcaster').value.trim(),creatorFeeRecipient:evmAccount};toast('Approve Pons v2 launch in wallet');const r=await launchPonsV2(input);if(r.receiptStatus!=='success')throw new Error('launch_transaction_reverted');if(r.token)saveTracked(r.token);toast(`Launch confirmed ${r.token?short(r.token):short(r.hash)}`);launchTab('portfolio');await loadPonsPortfolio()}catch(e){toast(String(e.shortMessage||e.message||e))}});
document.addEventListener('click',async e=>{const buy=e.target.closest('[data-pons-buy]'),sell=e.target.closest('[data-pons-sell]'),exp=e.target.closest('[data-pons-explorer]');if(exp){window.open(exp.dataset.ponsExplorer,'_blank','noopener');return}if(buy){const amt=Number(prompt('ETH to buy','0.01')||0);if(amt<=0)return;try{toast('Reading live curve quote');const r=await buyPons(buy.dataset.ponsBuy,amt);toast(`Buy confirmed · ${short(r.hash)}`);await loadPonsPortfolio()}catch(err){toast(String(err.shortMessage||err.message||err))}}if(sell){const amt=Number(prompt('Tokens to sell','1000')||0);if(amt<=0)return;try{toast('Approve token, then confirm sell');const r=await sellPons(sell.dataset.ponsSell,amt);toast(`Sell confirmed · ${short(r.hash)}`);await loadPonsPortfolio()}catch(err){toast(String(err.shortMessage||err.message||err))}}});
document.querySelectorAll('[data-nav="launch"]').forEach(b=>b.addEventListener('click',()=>loadPonsPortfolio()));
